### ISSUE TITLE
Authorize other auth backend

### ISSUE THREAD

**Issue by Seraf** [Docurated/concourse-vault-resource#5]
Hello,

I looking for a way to use this resource in a shared CI.
For example, I have teamA which is the customerA and teamB which is the customerB.

As they are executing their pipelines on the same pool of worker, the ec2 auth is not really secured as they share the same certificate/bound_ami/wathever.

I would like to avoid that my customerA try to replace the A with B and gain the access to all credentials of my other customer.

I was thinking to this backend : https://www.vaultproject.io/docs/auth/approle.html

Any idea ?

Thanks

**Comment by hexedpackets** [comment]
AppRole would work, although one thing to bear in mind is that it would require getting an initial secret from somewhere. If that's set in the pipeline config then anyone that can view the pipeline can get the secret back out. 

I think as long as the other team doesn't have access to the pipeline it would work for your case.

**Comment by Seraf** [comment]
Team shouldn't be able to view other's team's pipelines if I'm correct.
I think it's harder to guess a roleid + secretid than a simple role name as the nonce is defined by the client.

Do you think it's feasible to modify this resource to manage both authentication backend ?

**Comment by hexedpackets** [comment]
Yeah, I think having both multiple auth types is totally doable. Without looking into it too much, I think its just a matter of using a different authentication endpoint with the role and secret IDs instead of role and nonce.

**Comment by Seraf** [comment]
Yes, I don't think it should be too complicated.

I also found a problem with the current backend : I'm getting some secrets on a parallel jobs groups, and I get this error :

```
INFO: Reading secrets from: secret/******/ssh
Error writing data to auth/aws-ec2/login: Error making API request.

URL: PUT https://******/v1/auth/aws-ec2/login
Code: 400. Errors:

* failed to verify instance ID: error fetching description for instance ID "i-cd37de5b": "RequestLimitExceeded: Request limit exceeded.\n\tstatus code: 503, request id: dc484d48-cc87-4bc1-bd7b-a69c884aa85f"

ERROR: No token retrieved
Error reading secret/******/ssh: Error making API request.

URL: GET https://******/v1/secret/******/ssh
Code: 400. Errors:

* missing client token
```

The resource don't fail the job, but it should.
Maybe adding a retry on the curl to metadata could solve the problem.

Do you need help to implement this role id feature ?
