### ISSUE TITLE
Incorrect return value

### ISSUE THREAD

**Issue by xlr-8** [Docurated/concourse-vault-resource#7]
If a token is specified is invalid/missing then the call obviously fail, but seem to return 0 instead of an error, so the pipeline continue to run.

```bash
INFO: Reading secrets from: secret/test/ssh
Error writing data to auth/approle/login: Error making API request.

URL: PUT https://vault.test.io/v1/auth/approle/login
Code: 400. Errors:

* failed to validate SecretID: invalid secret_id "9824dcfe-xxxxxxxxxxxxxxxxxx"
ERROR: No token retrieved
Error reading secret/test/ssh: Error making API request.

URL: GET https://vault.test.io/v1/secret/test/ssh
Code: 400. Errors:

* missing client token
```

By any logic it should indeed be provided, but wasn't here due to a typo.
I think the faulty lines are the following: https://github.com/Docurated/concourse-vault-resource/blob/master/assets/common.sh#L4-L5

Because of the pipe it can hide errors, that should have exited with the -e flag set. E.g.:
```
$ cat test.sh
#!/bin/bash

set -e

source source.sh

echo "Test: end"

$ cat source.sh
#!/bin/bash

VAR=$(curl -s https://test.test/ -m 1 | tr -d '\n')
if [ -z "$VAR" ]; then
	echo "Source: Something wrong happened"
fi
echo "Source: end"

$ ./test.sh && echo "=> Success" || echo "=> Fail"
Source: Something wrong happened
Source: end
Test: end
=> Success

```

A way of fixing this would be to add whether a `return 1` (logical) or do an `exit 1` in the if checking the content of variables. The return would trigger the same behavior of exit as the return due to the `set -e` flag here: https://github.com/Docurated/concourse-vault-resource/blob/master/assets/in#L3
Or could be solved by splitting the calls with pipelines into several.

I believe similar problem could happen in https://github.com/Docurated/concourse-vault-resource/blob/master/assets/common.sh#L16-L18 as well.

**Comment by hexedpackets** [comment]
Nice catch, thanks for the fix.
